name: Upload Public Folder to S3

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the action on

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Upload public folder to S3
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your desired AWS region
        
    - name: Sync public folder with S3 bucket
      run: |
         aws s3 sync Website/mywebsite/public s3://${{ secrets.AWS_S3_BUCKET }} --delete --exact-timestamps --region us-east-1
